const faker = require("faker");
const fakerBr = require("faker-br");
const fs = require("fs");
const fileName = "./db.json";
const file = require(fileName);

const data = {
  batches: {
    content: [],
    message: "Ação Efetuada com Sucesso",
    typeResult: 1,
  },
  batch: {
    content: {
      id: faker.random.uuid(),
      companyName: faker.helpers.replaceSymbols("????"),
      date: faker.date.recent(),
      processedBillings: faker.random.number({ min: 0, max: 500 }),
      totalRunningBillings: faker.random.number({ min: 500, max: 1000 }),
      batchBillingType: faker.helpers.randomize(["Mensalidade", "Anual"]),
      billings: [],
      canceledBillings: faker.random.number({ min: 0, max: 500 }),
    },
    message: "Ação Efetuada com Sucesso",
    typeResult: 1,
  },
  billingDetailed: {
    content: {
      id: faker.random.uuid(),
      clientName: faker.helpers.replaceSymbols("????"),
      document: faker.helpers.randomize([fakerBr.br.cnpj(), fakerBr.br.cpf()]),
      contractCode: faker.helpers.replaceSymbols("????####"),
      billingCode: faker.helpers.replaceSymbols("????####"),
      rpsCode: faker.helpers.replaceSymbols("????####"),
      billingType: faker.helpers.randomize(["Mensalidade", "Anual"]),
      items: [],
    },
    message: "Ação Efetuada com Sucesso",
    typeResult: 1,
  },
  takers: {
    content: {
      personList: [
        {
          phone: "",
          email: "",
          id: 0,
          internalCode: "",
          name: "CULTURA INGLESA - MATRIZ",
          businessName: "CULTURA INGLESA IDIOMAS S.A",
          document: "17855050000153",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA SAO CLEMENTE",
              addressNumber: "258",
              addressComplement: "3 ANDAR",
              neighborhood: "BOTAFOGO",
              cityId: 3304557,
              cityName: "Rio de Janeiro",
              stateAcronym: "RJ",
              zipCode: "22260004",
              longitude: -43.19087,
              latitude: -22.949644,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "1937566896",
          email: "rafaela.rondelli@caepcampinas.com.br",
          id: 0,
          internalCode: "",
          name: "CAEP",
          businessName: "CENTRO AVANCADO DE ESTUDOS E PESQUISAS LTDA",
          document: "07339867000115",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "R JOSE GERALDO CEREBINO CHRISTOFARO",
              addressNumber: "245",
              addressComplement: "",
              neighborhood: "PARQUE RURAL FAZENDA SANTA CANDIDA",
              cityId: 3509502,
              cityName: "Campinas",
              stateAcronym: "SP",
              zipCode: "13087567",
              longitude: -47.050957,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "1120455900",
          email: "expedicao3@smscontabil.com.br",
          id: 0,
          internalCode: "",
          name: "MDS ESTRUTURAS METALICAS LTDA",
          businessName: "MDS ESTRUTURAS METALICAS LTDA",
          document: "30697302000121",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "AV AFONSO DE SAMPAIO E SOUSA",
              addressNumber: "2458",
              addressComplement: "",
              neighborhood: "ITAQUERA",
              cityId: 3550308,
              cityName: "São Paulo",
              stateAcronym: "SP",
              zipCode: "08270001",
              longitude: -46.467358,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "19000000000",
          email: "catrinevsantos@hotmail.com",
          id: 0,
          internalCode: "",
          name: "STARLIGHT MONTRA",
          businessName: "CATRINE VIEIRA DOS SANTOS 70046460683",
          document: "37066745000163",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "R PROFESSOR DOUTOR EURYCLIDES DE JESUS ZERBINI",
              addressNumber: "1841",
              addressComplement: "APTO 4",
              neighborhood: "PARQUE RURAL FAZENDA SANTA CANDIDA",
              cityId: 3509502,
              cityName: "Campinas",
              stateAcronym: "SP",
              zipCode: "13087571",
              longitude: -45.40337,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "1133033200",
          email: "financeiro@inmetrics.com.br",
          id: 0,
          internalCode: "",
          name: "INMETRICS S/A",
          businessName: "INMETRICS S/A",
          document: "04959158000225",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "AV TAMBORE",
              addressNumber: "267",
              addressComplement: "",
              neighborhood: "TAMBORE",
              cityId: 3505708,
              cityName: "Barueri",
              stateAcronym: "SP",
              zipCode: "06460000",
              longitude: -46.842834,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "1132442038",
          email: "cpacheco@oabsp.org.br",
          id: 0,
          internalCode: "",
          name: "OAB SP - MATRIZ",
          businessName: "ORDEM DOS ADVOGADOS DO BRASIL - SECCAO DE SAO PAULO",
          document: "43419613000170",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA ANCHIETA",
              addressNumber: "35",
              addressComplement: "TERREO",
              neighborhood: "CENTRO SE",
              cityId: 3550308,
              cityName: "São Paulo",
              stateAcronym: "SP",
              zipCode: "01016900",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "1135228009",
          email: "luiz.silveira@creditas.com",
          id: 0,
          internalCode: "",
          name: "CREDITAS - MATRIZ",
          businessName: "CREDITAS SOLUCOES FINANCEIRAS LTDA.",
          document: "17770708000124",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA IRMA GABRIELA",
              addressNumber: "51",
              addressComplement: "SALA 227",
              neighborhood: "CIDADE MONCOES",
              cityId: 3550308,
              cityName: "São Paulo",
              stateAcronym: "SP",
              zipCode: "04571130",
              longitude: -46.69444,
              latitude: -23.604197,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "69981276497",
          email: "",
          id: 0,
          internalCode: "",
          name: "LETICIA CALCAGNOTTO",
          businessName: "LETICIA CALCAGNOTTO",
          document: "78338816272",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA EUGENIO BONADIO",
              addressNumber: "335",
              addressComplement: "APE 43A",
              neighborhood: "CENTRO",
              cityId: 3549904,
              cityName: "São José dos Campos",
              stateAcronym: "SP",
              zipCode: "12245660",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "1141786961",
          email: "",
          id: 0,
          internalCode: "",
          name: "ADRIANA ALMEIDA MIGUEL",
          businessName: "ADRIANA ALMEIDA MIGUEL",
          document: "06683960836",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA GUARUJA",
              addressNumber: "38",
              addressComplement: "",
              neighborhood: "JARDIM RUBI",
              cityId: 3547304,
              cityName: "Santana de Parnaíba",
              stateAcronym: "SP",
              zipCode: "06502130",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "11992473232",
          email: "",
          id: 0,
          internalCode: "",
          name: "AMANDA CUNHA",
          businessName: "AMANDA CUNHA",
          document: "46399395828",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA DOUTOR ALBUQUERQUE LINS",
              addressNumber: "1184",
              addressComplement: "",
              neighborhood: "SANTA CECILIA",
              cityId: 3550308,
              cityName: "São Paulo",
              stateAcronym: "SP",
              zipCode: "01230000",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "11111111111",
          email: "sem e-mail",
          id: 0,
          internalCode: "",
          name: "AGIBANK - LOJA PROMIL - SALVADOR - ITAPUA",
          businessName: "BANCO AGIBANK S.A",
          document: "81002319587",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "AVENIDA DORIVAL CAYMMI",
              addressNumber: "14358",
              addressComplement: "LOJA A",
              neighborhood: "ITAPUA",
              cityId: 2927408,
              cityName: "Salvador",
              stateAcronym: "BA",
              zipCode: "41635150",
              longitude: -38.364273,
              latitude: -12.941259,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "11992691113",
          email: "",
          id: 0,
          internalCode: "",
          name: "SARAH SILVA",
          businessName: "SARAH SILVA",
          document: "38259746859",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA JURUA",
              addressNumber: "9",
              addressComplement: "",
              neighborhood: "CIDADE SANTA JULIA",
              cityId: 3522208,
              cityName: "Itapecerica da Serra",
              stateAcronym: "SP",
              zipCode: "06866540",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "11996827545",
          email: "",
          id: 0,
          internalCode: "",
          name: "ANITA BREJEIRO",
          businessName: "ANITA BREJEIRO",
          document: "16768755811",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "PRACA BOM JESUS DE PIRAPORINHA",
              addressNumber: "125",
              addressComplement: "OTICAS CAROL",
              neighborhood: "PIRAPORINHA",
              cityId: 3513801,
              cityName: "Diadema",
              stateAcronym: "SP",
              zipCode: "09951550",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "11987376389",
          email: "",
          id: 0,
          internalCode: "",
          name: "AMANDA GUEICHA RIBEIRO",
          businessName: "AMANDA GUEICHA RIBEIRO",
          document: "36115252865",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "AV. LAVANDISCA",
              addressNumber: "741",
              addressComplement: "CONJ 53",
              neighborhood: "MOEMA",
              cityId: 3550308,
              cityName: "São Paulo",
              stateAcronym: "SP",
              zipCode: "04515011",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "11942150934",
          email: "",
          id: 0,
          internalCode: "",
          name: "LUCIANA AP DE AZEVEDO",
          businessName: "LUCIANA AP DE AZEVEDO",
          document: "41073585859",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA FELIPE DO AMARAL",
              addressNumber: "400",
              addressComplement: "",
              neighborhood: "PORTAL SANTA F3",
              cityId: 3522406,
              cityName: "Itapeva",
              stateAcronym: "SP",
              zipCode: "13295000",
              longitude: -48.88039,
              latitude: -23.984911,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
        {
          phone: "48991839596",
          email: "",
          id: 0,
          internalCode: "",
          name: "FERNANDA GENOVEZ",
          businessName: "FERNANDA GENOVEZ",
          document: "02330015909",
          typeId: 0,
          registerTypeId: 0,
          internalNickName: "",
          externalNickName: "",
          registrationStateNumber: null,
          dataOrigemId: 2,
          statusId: 0,
          optingForTheSimple: false,
          addressList: [
            {
              id: 0,
              referenceId: 0,
              referenceOriginId: 0,
              typeId: 1,
              address: "RUA AMARILDO JOSE DA ROSA",
              addressNumber: "700",
              addressComplement: "",
              neighborhood: "HUMAITA",
              cityId: 4218707,
              cityName: "Tubarão",
              stateAcronym: "SC",
              zipCode: "88704460",
              longitude: 0,
              latitude: 0,
              statusId: 0,
              updateByUserId: 0,
            },
          ],
          updateByUserId: 0,
        },
      ],
      canRequest: true,
      message: null,
    },
    message: "Ação efetuada com sucesso.",
    typeResult: 1,
  },
  monthDetailed: {
    content: {
      id: faker.random.uuid(),
      clientName: faker.helpers.replaceSymbols("????"),
      document: faker.helpers.randomize([fakerBr.br.cnpj(), fakerBr.br.cpf()]),
      contractCode: faker.helpers.replaceSymbols("????####"),
      billingCode: faker.helpers.replaceSymbols("????####"),
      rpsCode: faker.helpers.replaceSymbols("????####"),
      billingType: faker.helpers.randomize(["Mensalidade", "Anual"]),
      price: faker.commerce.price(500, 1000),
      status: faker.helpers.randomize(["Ativo", "Inativo"]),
      items: [],
    },
    message: "Ação efetuada com sucesso",
    typeResult: 1,
  },
  surplusDetailed: {
    content: {
      id: faker.random.uuid(),
      clientName: faker.helpers.replaceSymbols("????"),
      document: faker.helpers.randomize([fakerBr.br.cnpj(), fakerBr.br.cpf()]),
      contractCode: faker.helpers.replaceSymbols("????####"),
      billingCode: faker.helpers.replaceSymbols("????####"),
      rpsCode: faker.helpers.replaceSymbols("????####"),
      billingType: faker.helpers.randomize(["Mensalidade", "Anual"]),
      price: faker.commerce.price(500, 1000),
      status: faker.helpers.randomize(["Ativo", "Inativo"]),
      items: [],
    },
    message: "Ação efetuada com sucesso",
    typeResult: 1,
  },
};

for (let i = 0; i < 20; i++) {
  data.batches.content.push({
    id: faker.random.uuid(),
    companyName: faker.helpers.replaceSymbols("????"),
    date: faker.date.recent(),
    processedBillings: faker.random.number({ min: 0, max: 500 }),
    totalRunningBillings: faker.random.number({ min: 500, max: 1000 }),
    batchBillingType: faker.helpers.randomize(["Mensalidade", "Anual"]),
  });

  data.batch.content.billings.push({
    id: faker.random.uuid(),
    clientName: faker.helpers.replaceSymbols("????"),
    document: faker.helpers.randomize([fakerBr.br.cnpj(), fakerBr.br.cpf()]),
    contractCode: faker.helpers.replaceSymbols("????####"),
    billingCode: faker.helpers.replaceSymbols("????####"),
    rpsCode: faker.helpers.replaceSymbols("????####"),
    batchBillingType: faker.helpers.randomize(["Mensalidade", "Anual"]),
    status: faker.helpers.randomize(["Ativo", "Inativo"]),
    createdAt: faker.date.recent(),
  });

  data.monthDetailed.content.items.push({
    id: faker.random.uuid(),
    clientName: faker.helpers.replaceSymbols("????"),
    monthlyPrice: faker.commerce.price(100, 1000),
    days: faker.random.number({ min: 1, max: 31 }),
    chargeAmount: faker.commerce.price(100, 1000),
    rpsCode: faker.helpers.replaceSymbols("????####"),
    status: faker.helpers.randomize(["Ativo", "Inativo"]),
  });

  data.surplusDetailed.content.items.push({
    id: faker.random.uuid(),
    clientName: faker.helpers.replaceSymbols("????"),
    contractedWeight: faker.commerce.price(100, 1000),
    surplusWeight: faker.commerce.price(1, 100),
    surplusPrice: faker.commerce.price(1, 10),
    rpsCode: faker.helpers.replaceSymbols("######"),
    rpsCode: faker.helpers.replaceSymbols("######"),
    status: faker.helpers.randomize(["Ativo", "Inativo"]),
  });
}

for (let i = 0; i < 5; i++) {
  data.billingDetailed.content.items.push({
    description: faker.helpers.randomize([
      "Mensalidade de Pontos",
      "Desconto",
      "Aditivo",
      "Cobrança de Excedente",
      "Mão de Obra",
      "Valor da Matriz",
    ]),
    document: faker.helpers.randomize([fakerBr.br.cnpj(), fakerBr.br.cpf()]),
    referenceDate: faker.date.recent(),
    billingType: faker.helpers.randomize(["Mensalidade", "Anual"]),
    price: faker.commerce.price(500, 1000),
  });
}

fs.writeFile(fileName, JSON.stringify(data), function writeJSON(err) {
  if (err) return console.log(err);
  console.log(JSON.stringify(file));
  console.log("writing to " + fileName);
});
